### ISSUE TITLE
What commit should I work off of?

### ISSUE THREAD

**Issue by MingweiSamuel** [Xaroth/libottdadmin2#13]
Is the latest commit working or is it WIP?

**Comment by MingweiSamuel** [comment]
Probably stable-0.0.2 huh

**Comment by Xaroth** [comment]
master would be recommended.

**Comment by MingweiSamuel** [comment]
Whats the replacement for `from libottdadmin2.trackingclient import TrackingAdminClient` in the rework?

**Comment by Xaroth** [comment]
There is no direct replacement, the examples dir has some examples on how this could easily be accomplished.

**Comment by MingweiSamuel** [comment]
So something with `TrackingMixIn, OttdAdminProtocol` ?

**Comment by Xaroth** [comment]
Correct. The examples should show most of the inner workings
